package by.epam.training.jwd.godot.controller.command;

public enum CommandName {
	LOGINATION, REGISTRATION, GOTOINDEXPAGE,
	LOGOUT, GOTOREGISTRATIONPAGE,GOTOLOGINATIONPAGE,GOTOADMINPAGE,
	GOTOMANAGEINGREDIENTSPAGE, MANAGEINGREDIENTS, SWITCHLANGUAGE
}
